// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

//ui_Arc1 = lv_arc_create(ui_Screen1);
//lv_obj_set_width( ui_Arc1, 80);
//lv_obj_set_height( ui_Arc1, 80);
//lv_obj_set_x( ui_Arc1, -28 );
//lv_obj_set_y( ui_Arc1, -16 );
//lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
//lv_arc_set_value(ui_Arc1, 50);

  lv_obj_t * spinner = lv_spinner_create(ui_Screen1);
  lv_obj_set_size(spinner, 64, 64);
  lv_obj_align(spinner, LV_ALIGN_CENTER, 0, 0);


ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_baseline_thumb_up_black_18dp_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 36
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
