// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: STM32Dev2

#include "ui.h"

void updateBaro1(lv_event_t * e)
{
	// Your code here
}

void updateTextArea(lv_event_t * e)
{
	// Your code here

	int a = 1;
}
